//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public static class BuildParameters
	{
		public static readonly DateTime Time = new DateTime(636815680500738825, DateTimeKind.Utc);
		public static readonly string UnityVersion = "2018.2.17f1";
		public static readonly string UnityPlatform = "WindowsEditor";
		public static readonly string OSVersion = "Microsoft Windows NT 10.0.17134.0";
		public static readonly string CurrentDirectory = "C:/Users/Jack The Ripper/Documents/GameDev/Rewind Networking/RewindNetworkingMK1";
		public static readonly string UserName = "Jack The Ripper";
		public static readonly bool Is64BitProcess = true;
	}
}
