//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

using System;

namespace Assets.Editor.GameDevWare.TextTranform.Examples
{
	public static class BuildParameters
	{
		public static readonly DateTime Time = new DateTime(638238481343720027, DateTimeKind.Utc);
		public static readonly string UnityVersion = "2022.3.3f1";
		public static readonly string UnityPlatform = "WindowsEditor";
		public static readonly string OSVersion = "Microsoft Windows NT 10.0.22621.0";
		public static readonly string CurrentDirectory = "C:/Users/ridde/Documents/PersonalGameDev/Rewind networking/Rewind_networking_git";
		public static readonly string UserName = "ridde";
		public static readonly bool Is64BitProcess = true;
	}
}
